### PR TITLE
Define macro for boost >= 1.66

### PR DESCRIPTION
**Pull request by trourance**
This is to fix the issue with raspbian buster #44

### CODE REVIEW

**Comment by cygnusxi** [comment]
@trourance can you test the current version on raspbian to see if this pull is still required? Thanks!

**Comment by trourance** [comment]
It seems that the master branch doesn't compile anymore.
I get the following error:
```
In file included from main.h:8,
                 from db.h:8,
                 from checkpoints.cpp:10:
bignum.h:104:5: error: ‘CBigNum::CBigNum(long long int)’ cannot be overloaded with ‘CBigNum::CBigNum(int64_t)’
     CBigNum(long long int n)      { init(); setuint64(n); }
     ^~~~~~~
bignum.h:98:5: note: previous declaration ‘CBigNum::CBigNum(int64_t)’
     CBigNum(int64_t n)            { init(); setint64(n); }
     ^~~~~~~
make: *** [makefile.raspberrypi:149: obj/checkpoints.o] Error 1
```

**Comment by Nuitari** [comment]
What versions of gcc and openssl do you have?

**Comment by trourance** [comment]
I've tried with both version of libssl, same result.
`gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)`
`libssl1.0-dev:armhf 1.0.2q-2` or `libssl-dev:armhf  1.1.1d-0+deb10u3+rpt1`

**Comment by pwnzjoon00b** [comment]
Nice, I was able to successfully build curecoind on my rPi making this change!

**Pull request merged**
